-- MySQL Script generated by MySQL Workbench
-- Tue Oct  1 09:24:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rector` (
  `id_Rector` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Rector`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vice_Rectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vice_Rectors` (
  `id_Vice_Rectors` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  `Rector_id_Rector` INT NOT NULL,
  PRIMARY KEY (`id_Vice_Rectors`),
  INDEX `fk_Academic_Vice_Rector_Rector1_idx` (`Rector_id_Rector` ASC) VISIBLE,
  CONSTRAINT `fk_Academic_Vice_Rector_Rector1`
    FOREIGN KEY (`Rector_id_Rector`)
    REFERENCES `mydb`.`Rector` (`id_Rector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Faculties` (
  `id_Faculties` INT NOT NULL AUTO_INCREMENT,
  `faculty_name` VARCHAR(45) NOT NULL,
  `Vice_Rectors_id_Vice_Rectors` INT NOT NULL,
  PRIMARY KEY (`id_Faculties`),
  INDEX `fk_Faculties_Vice_Rectors1_idx` (`Vice_Rectors_id_Vice_Rectors` ASC) VISIBLE,
  CONSTRAINT `fk_Faculties_Vice_Rectors1`
    FOREIGN KEY (`Vice_Rectors_id_Vice_Rectors`)
    REFERENCES `mydb`.`Vice_Rectors` (`id_Vice_Rectors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `id_Faculty_Courses` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  `Faculties_id_Faculties` INT NOT NULL,
  `duration` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Faculty_Courses`),
  INDEX `fk_Courses_Faculties1_idx` (`Faculties_id_Faculties` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Faculties1`
    FOREIGN KEY (`Faculties_id_Faculties`)
    REFERENCES `mydb`.`Faculties` (`id_Faculties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Head_of_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Head_of_department` (
  `id_Head_Department` INT NOT NULL AUTO_INCREMENT,
  `name(siranush)` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  `Faculties_id_Faculties` INT NOT NULL,
  PRIMARY KEY (`id_Head_Department`),
  INDEX `fk_Department_Faculties1_idx` (`Faculties_id_Faculties` ASC) VISIBLE,
  CONSTRAINT `fk_Department_Faculties1`
    FOREIGN KEY (`Faculties_id_Faculties`)
    REFERENCES `mydb`.`Faculties` (`id_Faculties`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Head_Of_chair`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Head_Of_chair` (
  `id_Head_Chair` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  `Courses_id_Faculty_Courses` INT NOT NULL,
  `Head_of_department_id_Head_Department` INT NOT NULL,
  PRIMARY KEY (`id_Head_Chair`),
  INDEX `fk_Head_Of_Department_Courses1_idx` (`Courses_id_Faculty_Courses` ASC) VISIBLE,
  INDEX `fk_Head_Of_chair_Head_of_department1_idx` (`Head_of_department_id_Head_Department` ASC) VISIBLE,
  CONSTRAINT `fk_Head_Of_Department_Courses1`
    FOREIGN KEY (`Courses_id_Faculty_Courses`)
    REFERENCES `mydb`.`Courses` (`id_Faculty_Courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Head_Of_chair_Head_of_department1`
    FOREIGN KEY (`Head_of_department_id_Head_Department`)
    REFERENCES `mydb`.`Head_of_department` (`id_Head_Department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `id_Group` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `Head_Of_chair_id_Head_Chair` INT NOT NULL,
  `Head_of_department_id_Head_Department` INT NOT NULL,
  PRIMARY KEY (`id_Group`),
  INDEX `fk_Group_Head_Of_chair1_idx` (`Head_Of_chair_id_Head_Chair` ASC) VISIBLE,
  INDEX `fk_Group_Head_of_department1_idx` (`Head_of_department_id_Head_Department` ASC) VISIBLE,
  CONSTRAINT `fk_Group_Head_Of_chair1`
    FOREIGN KEY (`Head_Of_chair_id_Head_Chair`)
    REFERENCES `mydb`.`Head_Of_chair` (`id_Head_Chair`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_Head_of_department1`
    FOREIGN KEY (`Head_of_department_id_Head_Department`)
    REFERENCES `mydb`.`Head_of_department` (`id_Head_Department`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `gendre` VARCHAR(45) NOT NULL,
  `nationality` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `gpa` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  `Group_id_Group` INT NOT NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `fk_Student_Group1_idx` (`Group_id_Group` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Group1`
    FOREIGN KEY (`Group_id_Group`)
    REFERENCES `mydb`.`Group` (`id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id_Teacher` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `paswword` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  `online_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Teacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Financial_Office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Financial_Office` (
  `id_Financial_Office` INT NOT NULL AUTO_INCREMENT,
  `Rector_id_Rector` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `recover_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Financial_Office`),
  INDEX `fk_Financial_Office_Rector1_idx` (`Rector_id_Rector` ASC) VISIBLE,
  CONSTRAINT `fk_Financial_Office_Rector1`
    FOREIGN KEY (`Rector_id_Rector`)
    REFERENCES `mydb`.`Rector` (`id_Rector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`semester` (
  `idsemester` INT NOT NULL AUTO_INCREMENT,
  `started_day` VARCHAR(45) NOT NULL,
  `end_day` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsemester`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subjects` (
  `id_subjects` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `Faculty_Courses_id_Faculty_Courses` INT NOT NULL,
  `semester_idsemester` INT NOT NULL,
  `Teacher_id_Teacher` INT NOT NULL,
  PRIMARY KEY (`id_subjects`),
  INDEX `fk_courses_Faculty_Courses1_idx` (`Faculty_Courses_id_Faculty_Courses` ASC) VISIBLE,
  INDEX `fk_courses_semester1_idx` (`semester_idsemester` ASC) VISIBLE,
  INDEX `fk_Subjects_Teacher1_idx` (`Teacher_id_Teacher` ASC) VISIBLE,
  CONSTRAINT `fk_courses_Faculty_Courses1`
    FOREIGN KEY (`Faculty_Courses_id_Faculty_Courses`)
    REFERENCES `mydb`.`Courses` (`id_Faculty_Courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_semester1`
    FOREIGN KEY (`semester_idsemester`)
    REFERENCES `mydb`.`semester` (`idsemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subjects_Teacher1`
    FOREIGN KEY (`Teacher_id_Teacher`)
    REFERENCES `mydb`.`Teacher` (`id_Teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student_Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student_Grade` (
  `id_Student_Grade` INT NOT NULL AUTO_INCREMENT,
  `exam_1` VARCHAR(45) NULL,
  `exam_2` VARCHAR(45) NULL,
  `final_exam` VARCHAR(45) NULL,
  `Student_idStudent` INT NOT NULL,
  `semester_idsemester` INT NOT NULL,
  `courses_idcourses` INT NOT NULL,
  PRIMARY KEY (`id_Student_Grade`),
  INDEX `fk_Student_Grade_semester1_idx` (`semester_idsemester` ASC) VISIBLE,
  INDEX `fk_Student_Grade_courses1_idx` (`courses_idcourses` ASC) VISIBLE,
  INDEX `fk_Student_Grade_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Grade_semester1`
    FOREIGN KEY (`semester_idsemester`)
    REFERENCES `mydb`.`semester` (`idsemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Grade_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `mydb`.`Subjects` (`id_subjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Grade_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_Groups` (
  `idTeacher_Enrolement` INT NOT NULL AUTO_INCREMENT,
  `Group_id_Group` INT NOT NULL,
  `Teacher_id_Teacher` INT NOT NULL,
  PRIMARY KEY (`idTeacher_Enrolement`),
  INDEX `fk_Teacher_Enrolement_Group1_idx` (`Group_id_Group` ASC) VISIBLE,
  INDEX `fk_Teacher_Enrolement_Teacher1_idx` (`Teacher_id_Teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Enrolement_Group1`
    FOREIGN KEY (`Group_id_Group`)
    REFERENCES `mydb`.`Group` (`id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Enrolement_Teacher1`
    FOREIGN KEY (`Teacher_id_Teacher`)
    REFERENCES `mydb`.`Teacher` (`id_Teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `idpayments` INT NOT NULL AUTO_INCREMENT,
  `paied` VARCHAR(45) NOT NULL,
  `total_payment` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `deadline_date` VARCHAR(45) NOT NULL,
  `Student_idStudent` INT NOT NULL,
  `semester_idsemester` INT NOT NULL,
  `Faculty_Courses_id_Faculty_Courses` INT NOT NULL,
  `Financial_Office_id_Financial_Office` INT NOT NULL,
  PRIMARY KEY (`idpayments`),
  INDEX `fk_payments_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  INDEX `fk_payments_Financial_Office1_idx` (`Financial_Office_id_Financial_Office` ASC) VISIBLE,
  INDEX `fk_payments_semester1_idx` (`semester_idsemester` ASC) VISIBLE,
  INDEX `fk_payments_Faculty_Courses1_idx` (`Faculty_Courses_id_Faculty_Courses` ASC) VISIBLE,
  CONSTRAINT `fk_payments_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `mydb`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_Financial_Office1`
    FOREIGN KEY (`Financial_Office_id_Financial_Office`)
    REFERENCES `mydb`.`Financial_Office` (`id_Financial_Office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_semester1`
    FOREIGN KEY (`semester_idsemester`)
    REFERENCES `mydb`.`semester` (`idsemester`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payments_Faculty_Courses1`
    FOREIGN KEY (`Faculty_Courses_id_Faculty_Courses`)
    REFERENCES `mydb`.`Courses` (`id_Faculty_Courses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_Store` (
  `id_Teacher_Store` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `pdf_file` MEDIUMBLOB NULL,
  `Teacher_id_Teacher` INT NOT NULL,
  PRIMARY KEY (`id_Teacher_Store`),
  INDEX `fk_Teacher_Store_Teacher1_idx` (`Teacher_id_Teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Store_Teacher1`
    FOREIGN KEY (`Teacher_id_Teacher`)
    REFERENCES `mydb`.`Teacher` (`id_Teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat_store` (
  `idchat_strore` INT NOT NULL AUTO_INCREMENT,
  `conversation` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `from` INT NOT NULL,
  `to` INT NOT NULL,
  `from_type` VARCHAR(45) NOT NULL,
  `to_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idchat_strore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Email_Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Email_Store` (
  `idEmail_Store` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `contant` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `pdf` MEDIUMBLOB NULL,
  `from` INT NOT NULL,
  `to` INT NOT NULL,
  `from_type` VARCHAR(45) NOT NULL,
  `to_tyoe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmail_Store`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher_Group_Email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher_Group_Email` (
  `idTeacher_Group_Email` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `contant` VARCHAR(45) NOT NULL,
  `pdf` MEDIUMBLOB NULL,
  `date` VARCHAR(45) NOT NULL,
  `perpose` VARCHAR(45) NOT NULL,
  `Group_id_Group` INT NOT NULL,
  `Teacher_id_Teacher` INT NOT NULL,
  PRIMARY KEY (`idTeacher_Group_Email`),
  INDEX `fk_Teacher_Group_Email_Group1_idx` (`Group_id_Group` ASC) VISIBLE,
  INDEX `fk_Teacher_Group_Email_Teacher1_idx` (`Teacher_id_Teacher` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Group_Email_Group1`
    FOREIGN KEY (`Group_id_Group`)
    REFERENCES `mydb`.`Group` (`id_Group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Group_Email_Teacher1`
    FOREIGN KEY (`Teacher_id_Teacher`)
    REFERENCES `mydb`.`Teacher` (`id_Teacher`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Main_Page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Main_Page` (
  `idMain_Page` INT NOT NULL AUTO_INCREMENT,
  `cover_photo` LONGBLOB NOT NULL,
  `cover_photo_2` LONGBLOB NOT NULL,
  `about_us` VARCHAR(45) NOT NULL,
  `admission` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `tell` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMain_Page`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`events` (
  `idevents` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `contant` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `Main_Page_idMain_Page` INT NOT NULL,
  PRIMARY KEY (`idevents`),
  INDEX `fk_events_Main_Page1_idx` (`Main_Page_idMain_Page` ASC) VISIBLE,
  CONSTRAINT `fk_events_Main_Page1`
    FOREIGN KEY (`Main_Page_idMain_Page`)
    REFERENCES `mydb`.`Main_Page` (`idMain_Page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gallary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gallary` (
  `idGallary` INT NOT NULL AUTO_INCREMENT,
  `image` LONGBLOB NOT NULL,
  `Main_Page_idMain_Page` INT NOT NULL,
  PRIMARY KEY (`idGallary`),
  INDEX `fk_Gallary_Main_Page1_idx` (`Main_Page_idMain_Page` ASC) VISIBLE,
  CONSTRAINT `fk_Gallary_Main_Page1`
    FOREIGN KEY (`Main_Page_idMain_Page`)
    REFERENCES `mydb`.`Main_Page` (`idMain_Page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses_web`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses_web` (
  `idcourses` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `contant` VARCHAR(45) NOT NULL,
  `img` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `duration_date` VARCHAR(45) NOT NULL,
  `Main_Page_idMain_Page` INT NOT NULL,
  PRIMARY KEY (`idcourses`),
  INDEX `fk_courses_Main_Page1_idx` (`Main_Page_idMain_Page` ASC) VISIBLE,
  CONSTRAINT `fk_courses_Main_Page1`
    FOREIGN KEY (`Main_Page_idMain_Page`)
    REFERENCES `mydb`.`Main_Page` (`idMain_Page`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_Enrollement_Accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_Enrollement_Accounts` (
  `idCourse_Enrollement_Accounts` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surename` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `courses_idcourses` INT NOT NULL,
  PRIMARY KEY (`idCourse_Enrollement_Accounts`),
  INDEX `fk_Course_Enrollement_Accounts_courses1_idx` (`courses_idcourses` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Enrollement_Accounts_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `mydb`.`courses_web` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Out_Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Out_Payments` (
  `idOut_Payments` INT NOT NULL AUTO_INCREMENT,
  `paied` VARCHAR(45) NOT NULL,
  `total_payment` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `deadline_date` VARCHAR(45) NOT NULL,
  `Financial_Office_id_Financial_Office` INT NOT NULL,
  `Course_Enrollement_Accounts_idCourse_Enrollement_Accounts` INT NOT NULL,
  PRIMARY KEY (`idOut_Payments`),
  INDEX `fk_Out_Payments_Financial_Office1_idx` (`Financial_Office_id_Financial_Office` ASC) VISIBLE,
  INDEX `fk_Out_Payments_Course_Enrollement_Accounts1_idx` (`Course_Enrollement_Accounts_idCourse_Enrollement_Accounts` ASC) VISIBLE,
  CONSTRAINT `fk_Out_Payments_Financial_Office1`
    FOREIGN KEY (`Financial_Office_id_Financial_Office`)
    REFERENCES `mydb`.`Financial_Office` (`id_Financial_Office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Out_Payments_Course_Enrollement_Accounts1`
    FOREIGN KEY (`Course_Enrollement_Accounts_idCourse_Enrollement_Accounts`)
    REFERENCES `mydb`.`Course_Enrollement_Accounts` (`idCourse_Enrollement_Accounts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
